startDate: 2015-04-01               # All activities after this date will be aggregated
outputFilename: stravaDump.json

abreviatedAttributes:               # Activity attributes to store in the abreviated strava dump
-   name
-   distance
-   moving_time
-   total_elevation_gain
-   start_latlng
-   end_latlng
-   map
-   average_speed
-   max_speed

statisticize:                       # Activity attributes to compute statistics for
-   attribute: distance
    statistic: total

-   attribute: distance
    statistic: dailyAverage 

-   attribute: total_elevation_gain
    statistic: total